- name: Copy mongo.repo
  ansible.builtin.copy:
    src: /home/ec2-user/ansible-roboshop/mongo.repo/
    dest: /etc/yum.repos.d/mongo.repo

- name:  install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
    
- name: enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true
- name: enable remote connections to mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: restart mongod
  ansible.builtin.service:
    name: mongod
    state: restarted     
