- name: installing roboshop project 
  hosts: "{{component}}"
  become: yes
  roles:
  - "{{component}}"


  # ansible-playbook -e ansible_user=ec2-user -e ansible_password=DevOps321 -e component=mongodb -i inventory main.yaml
#This is the command we should run from ansible server