- name: Install Nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs


- name: setup applcation
  ansible.builtin.import_role:
    name: common
    tasks_from: app_set_up

- name: install dependinces
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: load mongo schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load_mongo_schema



- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup

  