- name: check the roboshop user exit or not
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true

- name: create user
  when: out.rc != 0     
  ansible.builtin.user:
    name: roboshop
- name: checking the directory
  ansible.builtin.stat:
    path: /app
  register: dir_status
- name: create /app directory
  when: dir_status.stat.exists == False
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download catalogue.zip to /tmp
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp/catalogue.zip  
- name: unzip the catalogue.zip into /app dir_status
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes