- name: check the roboshop user exit or not
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true

- name: create user
  when: out.rc != 0     
  ansible.builtin.user:
    name: roboshop

- name: checking the directory
  ansible.builtin.stat:
    path: /app
  register: dir_status

- name: create /app directory
  when: dir_status.stat.exists == False
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download {{component}}  to /tmp
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp/{{component}}.zip 

- name: unzip the {{component}} .zip into /app dir_status
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes